const ActionTypes = {
  INCREMENT_COUNTER: "INC_COUNTER",
  DECREMENT_COUNTER: "DEC_COUNTER",
  ADD_COUNTER: "ADD_COUNTER",
  SUBTRACT_COUNTER: "SUB_COUNTER",
  STORE_RESULTS: "STORE_RESULTS",
  DELETE_RESULT: "DEL_RESULT",
};

export default ActionTypes;
